queries = [
    # +----------------+
    # |     GROUP1     |
    # +----------------+
    # +---------------+
    # |  Magistrates  |
    # +---------------+
    {
        "item_name": "Magistrates",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Opening File"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Sr No.", object),
                    ("Matter Type", str),
                    ("Email", object),
                    ("Previous Number", object),
                    ("CRIME", object),
                    ("File No.", object),
                    ("Date Opened", object),
                    ("Fee Earner", object),
                    ("Client's Surname", object),
                    ("Client's Forename(s)", object),
                    ("Client's Title", object),
                    ("Marital Status", object),
                    ("Letters to Home Address", object),
                    ("Address", object),
                    ("Postcode", object),
                    ("Postal Address (if Different)", object),
                    ("Postal Address Postcode", object),
                    ("Home Telephone", object),
                    ("Work Telephone", object),
                    ("Mobile Number", object),
                    ("Occupation", object),
                    ("Date of Birth", object),
                    ("Ethnicity", object),
                    ("Prison Number", object),
                    ("National Insurance Number", object),
                    ("3rd Party", object),
                    ("Initial", object),
                    ("Conflict", object),
                    ("Date", object),
                    ("Costs Information", str),
                    ("Cost Estimate", object),
                    ("Charge Basis", object),
                    ("Court", object),
                    ("Legal Aid", object),
                ],
            },
            {
                "operation": "remove_columns",
                "arguments": [
                    "Sr No.",
                    "Previous Number",
                    "CRIME",
                    "Date Opened",
                    "Client's Title",
                    "Marital Status",
                    "Letters to Home Address",
                    "Postal Address (if Different)",
                    "Postal Address Postcode",
                    "Home Telephone",
                    "Work Telephone",
                    "Occupation",
                    "Date of Birth",
                    "Ethnicity",
                    "3rd Party",
                    "Initial",
                    "Conflict",
                    "Date",
                    "Costs Information",
                    "Cost Estimate",
                    "Charge Basis",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Court == 'Magistrates'"],  # Filter condition
            },
            {
                "operation": "remove_columns",
                "arguments": ["Court"],  # Optional: Remove "Court" after filtering
            },
        ],
    },
    # +---------------+
    # |  Crown Court  |
    # +---------------+
    {
        "item_name": "Crown Court",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Opening File"},
            },
            {
                "operation": "change_type",
                "arguments": [
                    ("Sr No.", object),
                    ("Matter Type", str),
                    ("Email", object),
                    ("Previous Number", object),
                    ("CRIME", object),
                    ("File No.", object),
                    ("Date Opened", object),
                    ("Fee Earner", object),
                    ("Client's Surname", object),
                    ("Client's Forename(s)", object),
                    ("Client's Title", object),
                    ("Marital Status", object),
                    ("Letters to Home Address", object),
                    ("Address", object),
                    ("Postcode", object),
                    ("Postal Address (if Different)", object),
                    ("Postal Address Postcode", object),
                    ("Home Telephone", object),
                    ("Work Telephone", object),
                    ("Mobile Number", object),
                    ("Occupation", object),
                    ("Date of Birth", object),
                    ("Ethnicity", object),
                    ("Prison Number", object),
                    ("National Insurance Number", object),
                    ("3rd Party", object),
                    ("Initial", object),
                    ("Conflict", object),
                    ("Date", object),
                    ("Costs Information", str),
                    ("Cost Estimate", object),
                    ("Charge Basis", object),
                    ("Court", object),
                    ("Legal Aid", object),
                ],
            },
            {
                "operation": "remove_columns",
                "arguments": [
                    "Sr No.",
                    "Previous Number",
                    "CRIME",
                    "Date Opened",
                    "Client's Title",
                    "Marital Status",
                    "Letters to Home Address",
                    "Postal Address (if Different)",
                    "Postal Address Postcode",
                    "Home Telephone",
                    "Work Telephone",
                    "Occupation",
                    "Date of Birth",
                    "Ethnicity",
                    "3rd Party",
                    "Initial",
                    "Conflict",
                    "Date",
                    "Costs Information",
                    "Cost Estimate",
                    "Charge Basis",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Court == 'Crown/County'"],  # Filter condition
            },
            {
                "operation": "remove_columns",
                "arguments": ["Court"],  # Optional: Remove "Court" after filtering
            },
        ],
    },
    # +----------------+
    # |  Road Traffic  |
    # +----------------+
    {
        "item_name": "Road Traffic",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Opening File"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Sr No.", object),
                    ("Matter Type", str),
                    ("Email", object),
                    ("Previous Number", object),
                    ("CRIME", object),
                    ("File No.", object),
                    ("Date Opened", object),
                    ("Fee Earner", object),
                    ("Client's Surname", object),
                    ("Client's Forename(s)", object),
                    ("Client's Title", object),
                    ("Marital Status", object),
                    ("Letters to Home Address", object),
                    ("Address", object),
                    ("Postcode", object),
                    ("Postal Address (if Different)", object),
                    ("Postal Address Postcode", object),
                    ("Home Telephone", object),
                    ("Work Telephone", object),
                    ("Mobile Number", object),
                    ("Occupation", object),
                    ("Date of Birth", object),
                    ("Ethnicity", object),
                    ("Prison Number", object),
                    ("National Insurance Number", object),
                    ("3rd Party", object),
                    ("Initial", object),
                    ("Conflict", object),
                    ("Date", object),
                    ("Costs Information", str),
                    ("Cost Estimate", object),
                    ("Charge Basis", object),
                    ("Court", object),
                ],
            },
            {
                "operation": "remove_columns",
                "arguments": [
                    "Sr No.",
                    "Previous Number",
                    "CRIME",
                    "Date Opened",
                    "Fee Earner",
                    "Client's Title",
                    "Marital Status",
                    "Letters to Home Address",
                    "Postal Address (if Different)",
                    "Postal Address Postcode",
                    "Home Telephone",
                    "Work Telephone",
                    "Occupation",
                    "Date of Birth",
                    "Ethnicity",
                    "Prison Number",
                    "National Insurance Number",
                    "3rd Party",
                    "Initial",
                    "Conflict",
                    "Date",
                    "Costs Information",
                    "Cost Estimate",
                    "Charge Basis",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Court == 'Road Traffic'"],  # Filter condition
            },
            {
                "operation": "remove_columns",
                "arguments": ["Court"],
            },
        ],
    },
    # +------------------+
    # |  Police Station  |
    # +------------------+
    {
        "item_name": "Police Station",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Opening File"},
            },
            {
                "operation": "change_type",
                "arguments": [
                    ("Sr No.", object),
                    ("Matter Type", str),
                    ("Email", object),
                    ("Previous Number", object),
                    ("CRIME", object),
                    ("File No.", object),
                    ("Date Opened", object),
                    ("Fee Earner", object),
                    ("Client's Surname", object),
                    ("Client's Forename(s)", object),
                    ("Client's Title", object),
                    ("Marital Status", object),
                    ("Letters to Home Address", object),
                    ("Address", object),
                    ("Postcode", object),
                    ("Postal Address (if Different)", object),
                    ("Postal Address Postcode", object),
                    ("Home Telephone", object),
                    ("Work Telephone", object),
                    ("Mobile Number", object),
                    ("Occupation", object),
                    ("Date of Birth", object),
                    ("Ethnicity", object),
                    ("Prison Number", object),
                    ("National Insurance Number", object),
                    ("3rd Party", object),
                    ("Initial", object),
                    ("Conflict", object),
                    ("Date", object),
                    ("Costs Information", str),
                    ("Cost Estimate", object),
                    ("Charge Basis", object),
                    ("Court", object),
                    ("Legal Aid", object),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Fee Earner",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Marital Status",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "Occupation",
                    "Date of Birth",
                    "Ethnicity",
                    "HMP",
                    "Prison Number",
                    "National Insurance Number",
                    "Court",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Court == 'Police Station'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Fee Earner",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Marital Status",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "Occupation",
                    "Date of Birth",
                    "Ethnicity",
                    "HMP",
                    "Prison Number",
                    "National Insurance Number",
                ],
            },
        ],
    },
    # +----------+
    # |  group2  |
    # +----------+
    # +-----------+
    # |  Appeals  |
    # +-----------+
    {
        "item_name": "Appeals",
        "quires": [
            {
                "operation": "combine_sheets",
                "arguments": [
                    "Appeals - Magistrates",
                    "Appeals - Crown Court",
                    "Appeals - Road Traffic",
                ],
            },
        ],
    },
    # +---------------------+
    # |  Magistrates_Merge  |
    # +---------------------+
    {
        "item_name": "Magistrates Merge",
        "quires": [
            {
                "operation": "combine_sheets",
                "arguments": ["Magistrates", "PoliceStation to Magistrates"],
            },
        ],
    },
    # +---------------------+
    # |  Crown Court Merge  |
    # +---------------------+
    {
        "item_name": "Crown Court Merge",
        "quires": [
            {
                "operation": "combine_sheets",
                "arguments": [
                    "Crown Court",
                    "Magistrates to Crown Court 1",
                    "Magistrates to Crown Court 2",
                ],
            },
        ],
    },
    # +-----------+
    # |  group 3  |
    # +-----------+
    # +--------+
    # |  Bail  |
    # +--------+
    {
        "item_name": "Bail",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Police_Station"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("Mobile Number", str),
                    ("Date", object),
                    ("Fee Earner", object),
                    ("Date of Birth", object),
                    ("Occupation", object),
                    ("City", object),
                    ("Postcode", object),
                    ("Marital Status", object),
                    ("Ethnic Background", object),
                    ("Gender", object),
                    ("Nationality", object),
                    ("Offence Details", object),
                    ("Police Station", object),
                    ("Custody No.", object),
                    ("Officer in Case", object),
                    ("OIC Email", object),
                    ("OIC Phone Number", object),
                    ("Duty Ref No.", object),
                    ("Telephone No.", object),
                    ("Time of Arrest", object),
                    ("Time of Arrival at P/S", object),
                    ("Det Author", object),
                    ("Contacted by DSCC", object),
                    ("Time of Advice Call", object),
                    ("Outcome", object),
                    ("Next Date", object),
                    ("Time", object),
                    ("Location", object),
                    ("Has Result Been Diarised", object),
                    ("Co-Accused", object),
                    ("Conflict", object),
                    ("Name of Co-Accused", object),
                    ("Represented by", object),
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Outcome == 'Bail'"],  # Filter condition
            },
        ],
    },
    # +-------------------------+
    # |  Appeals - Magistrates  |
    # +-------------------------+
    {
        "item_name": "Appeals - Magistrates",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Magistrates_Merge"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("City", object),
                    ("Postcode", str),
                    ("Mobile Number", str),
                    ("HMP", object),
                    ("Court", object),
                    ("Offence", object),
                    ("Type of Offence", object),
                    ("First Hearing Date", object),
                    ("Outcome First Hearing", object),
                    ("Type of Letter", object),
                    ("Letter Issued", object),
                    ("Second Hearing Date", object),
                    ("Type of Letter 2", object),
                    ("Outcome Second Hearing", object),
                    ("Appeal", str),
                    ("Type of Letter 3", object),
                    ("Letter Issued2", object),
                    ("Legal Aid", object),
                    ("Matt Number (If Legal Aid Granted)", object),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "Appeal",
                ],
            },
            # BUG check if condition is yes
            {
                "operation": "filter_rows",
                "arguments": ["Appeal == 'Yes'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                ],
            },
        ],
    },
    # +-------------------------+
    # |  Appeals - Crown Court  |
    # +-------------------------+
    {
        "item_name": "Appeals - Crown Court",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Crown_Court_Merge"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("City", object),
                    ("Postcode", str),
                    ("Mobile Number", str),
                    ("HMP", object),
                    ("Court", object),
                    ("Name of Counsel", object),
                    ("Counsel Email Address", object),
                    ("Chambers", object),
                    ("PTPH Date", object),
                    ("Type of Letter", object),
                    ("Letter Sent?", object),
                    ("Stage 1", object),
                    ("Stage 2", object),
                    ("Stage 3", object),
                    ("Stage 4", object),
                    ("CTR Date", object),
                    ("Trial Date", object),
                    ("Outcome", object),
                    ("Type of Letter 2", object),
                    ("Appeal", str),
                    ("Legal Aid", object),
                    ("Matt Number (If Legal Aid Granted)", object),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "Appeal",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Appeal == 'Yes'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                ],
            },
        ],
    },
    # +--------------------------+
    # |  Appeals - Road Traffic  |
    # +--------------------------+
    {
        "item_name": "Appeals - Road Traffic",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Road_Traffic"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("City", object),
                    ("Postcode", str),
                    ("Mobile Number", str),
                    ("HMP", object),
                    ("Court", object),
                    ("Matter", object),
                    ("First Hearing", object),
                    ("Letter Issued", object),
                    ("Trial", object),
                    ("Letter Issued 2", object),
                    ("Outcome", object),
                    ("Appeal", str),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "Appeal",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Appeal == 'Yes'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                ],
            },
        ],
    },
    # +--------------------------------+
    # |  PoliceStation to Magistrates  |
    # +--------------------------------+
    {
        "item_name": "PoliceStation to Magistrates",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Police_Station"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("City", object),
                    ("Postcode", str),
                    ("Mobile Number", str),
                    ("Date", object),
                    ("Fee Earner", object),
                    ("Date of Birth", object),
                    ("Occupation", object),
                    ("Marital Status", object),
                    ("Ethnic Background", object),
                    ("Gender", object),
                    ("Nationality", object),
                    ("Offence Details", object),
                    ("Police Station", object),
                    ("Custody No.", object),
                    ("Officer in Case", object),
                    ("OIC Email", object),
                    ("OIC Phone Number", object),
                    ("Duty Ref No.", object),
                    ("Telephone No.", object),
                    ("Time of Arrest", object),
                    ("Time of Arrival at P/S", object),
                    ("Det Author", object),
                    ("Contacted by DSCC", object),
                    ("Time of Advice Call", object),
                    ("Outcome", str),
                    ("Type of Letter", object),
                    ("Next Date", object),
                    ("Time", object),
                    ("Location", object),
                    ("Has Result Been Diarised", object),
                    ("Co-Accused", object),
                    ("Conflict", object),
                    ("Name of Co-Accused", object),
                    ("Represented by", object),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "Outcome",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["Outcome == 'Charged'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                ],
            },
        ],
    },
    # +--------------------------------+
    # |  Magistrates to Crown Court 1  |
    # +--------------------------------+
    {
        "item_name": "Magistrates to Crown Court 1",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Magistrates_Merge"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("City", object),
                    ("Postcode", str),
                    ("Mobile Number", str),
                    ("HMP", object),
                    ("Court", object),
                    ("Offence", object),
                    ("Type of Offence", str),
                    ("First Hearing Date", object),
                    ("Outcome First Hearing", object),
                    ("Type of Letter", object),
                    ("Letter Issued", object),
                    ("Second Hearing Date", object),
                    ("Type of Letter 2", object),
                    ("Outcome Second Hearing", object),
                    ("Appeal", str),
                    ("Type of Letter 3", object),
                    ("Letter Issued2", object),
                    ("Legal Aid", object),
                    ("Matt Number (If Legal Aid Granted)", object),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "HMP",
                    "Type of Offence",
                ],
            },
            # BUG: filter_rows have space doesn't check
            {
                "operation": "filter_rows",
                "arguments": ["'Type of Offence' == 'Indictable'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "HMP",
                ],
            },
        ],
    },
    # +--------------------------------+
    # |  Magistrates to Crown Court 2  |
    # +--------------------------------+
    {
        "item_name": "Magistrates to Crown Court 2",
        "quires": [
            {
                "operation": "read",
                "arguments": {"sheet_name": "Magistrates_Merge"},
            },  # Read data (already handled)
            {
                "operation": "change_type",
                "arguments": [
                    ("Office", str),
                    ("Matter Type", str),
                    ("Email", str),
                    ("File No.", object),
                    ("Client's Surname", str),
                    ("Client's Forename(s)", str),
                    ("Address", str),
                    ("City", object),
                    ("Postcode", str),
                    ("Mobile Number", str),
                    ("HMP", object),
                    ("Court", object),
                    ("Offence", object),
                    ("Type of Offence", str),
                    ("First Hearing Date", object),
                    ("Outcome First Hearing", object),
                    ("Type of Letter", object),
                    ("Letter Issued", object),
                    ("Second Hearing Date", object),
                    ("Type of Letter 2", object),
                    ("Outcome Second Hearing", object),
                    ("Appeal", str),
                    ("Type of Letter 3", object),
                    ("Letter Issued2", object),
                    ("Legal Aid", object),
                    ("Matt Number (If Legal Aid Granted)", object),
                ],
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "HMP",
                    "Type of Offence",
                ],
            },
            {
                "operation": "filter_rows",
                "arguments": ["'Type of Offence' == 'Either Way'"],  # Filter condition
            },
            {
                "operation": "select_columns",
                "arguments": [
                    "Office",
                    "Matter Type",
                    "Email",
                    "File No.",
                    "Client's Surname",
                    "Client's Forename(s)",
                    "Address",
                    "City",
                    "Postcode",
                    "Mobile Number",
                    "HMP",
                ],
            },
        ],
    },
]
